language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key: 0b886747-6664-4cd6-92ad-c08f0e2296ea
  app: viewing-party
  run: rails db:migrate
env:
  global:
    secure: wggIKAp1YdizBIdEI15TQSR569iPKSlVINtF+9VGGISk3DNNVrspj/rrvwg93SuVgcvhIrE3bM313FDjZnsUzp+Ff9ry6TEsfW0xI3jMSFdnZKYfsfYi/T0ZPo8yFkvkTOP88KW1Hu9stjWdg59X5NTxcedPcvC/VJTkm/DA8UGMMS6fYQdXX27xUpETllNEl/Oqjqb2jDy4qXWYyQMNgT/KHGIXIVvhif5jZ79UynJLhf00JEPhSa/9mPEDnbaqEaXBO3ieonywlc35v+PP5udneHtPe2P4y8MiGYoVxhnFdv2eByvLMXO+ZooVhYg09o96GJL2Hqf9bp06EZ5LOzczo/LUGFG5TMfSMTIbunpg92hwvexX45xxbLu/6+zOtmiagWzDEK1P/34tMYh2g/CzVE6/qbUdgDJxEQaBcunOhfBjdgwQM2pLaZiXPi7V1P3p7qwC5nRL49yjZuAC4pEgtg54GkZi+4XGuWcWsMRsDd7XxHzOuTPQ+dMFrpUxT9/fZW4AHDkCaUflSoo9R5xEoUK2AyFBwpDBlKMxWIJBxvrxKsEncMO2bUsHgVqRyHIBHkn+lDcKgeINh5VkaVM2LQhCjgysuS5Y+j/J8FKtAzkCXfx2LY6BPf1guuEz/XGhFvwUMIbM95pz2GCi6A9IIV4CQdjBPMVNve7NxKA=
