language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key: 0b886747-6664-4cd6-92ad-c08f0e2296ea
  app: viewing-party
  run: rails db:migrate
env:
  matrix:
  - secure: MQttwWxtYhIlYkgdf16tRZQ1dr1QevRIdieT9cNVQCBlxMLXlRuo1b8EDnQ0LRyfXgUQjMXkWmwdmXUSSYJM3EoznaSqp51KsrVuuqfD2tptycO/0hyLgTTPEeyajKQ03iDxUxKDw9Zo8JceX70DzxmislHdqqTa7uoFM1xzxNpCTYfOxSSt93tg9SM46oxi0Dft23W5vuuDNOw+BdWYTFnJOh/9PeMd5PKwrHC+8xSfacGOkSuu/kKLa9LZL9CPy3DGMGL8NPrhYOzZW4aATSlM+k9j87ljdXlOr9zNYeRr9U9JFjOIHVAuA1a4nGCmFvW0FQ/3ojZ3X3xdmf9lE0HQ1lT8bS5toKwpausAObx1EYDJNIf7/lqYy7aruW5XHiEebhcQG/gWD9QFGACNmhC5PxeZZ9pTG9ro9sc0GnWF9ydUOPf2msZdEsqvKeMPIolTjbsBpvhKBCR5D7QvzBuTR/ts5dQmoUs4vpl8U3kmcDKG/09H1EZu6BE1AZZqA/EDGMag7ljBXNsZyhE+QreOHDPmUSfO/tKSeXyhaxadlpxMiATo0v8iuL4hsIT4SrR+92m5v7y+ngQDvXwfQlqU0PXBM9qikjNRwCTlHGisjejwqA1e7HJe3vDdYADPCIknOOSWLrOU8bTzy+RVD8obPStTLWbprJzSdeoqp74=
  global:
    secure: H0SuLFRhqfriw7VwpHR46BOgGJfBUHvkK3lTqEfbzi+prDsPdQJ85/1PKHWhMHU9Iiwu/MJ8QAjWR5R800JzAW6KaqGWholtMZvlVU/hJBoK3dsSoFw8n2+Ig2DqnZ0cXc1XlJODdC6SGOGULftjQGoVK0UeTcs/O1puYKMBo3epykzBiGdc9QmsEEBtzyBxe2sVtCmAichQjjYKESaz/MP/DfHC5U74FcCrPbB39+THhynWHQ3RNvTfnALdVx/sFZ32BYewN+yDJUxrxZ9vyhXBOExvAvVSTdr2sRVvlNAn8UluEzRv3R0rfBHgoAbcvnGWNy/9i7CIDVno1WIpXO8kIbNGfqnDMMy6OPUVeTKz2HqKY+RYpOxmLdzGDTcbrMhW5LA5vERBsY48wUnyWZu2fi+vIo3srWUhoD8rc7c+LJJZJFSdhHkScL2gAL8pOhNj90rgO0rB8/2Y+Yihj9COSOfp7JY89R0xf/4ODLy9/lgVJsLyyoAlDB5lt9jSN5We9ito7sTIkKRR7I4kSewKzoEIHNkNt29Kk5N7wL+hq8U3oGL3NGMbesDOcAJMA7H5mfC1wZTpbV0fxDex+yITMudD3yI+LRYyS2587/CMLf0IfdhNHvaw6ovs5nBtKpldWenKgImjBgYlMVaBLiAqtzaKqMxvi3vrltrYKe8=
