language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key: 0b886747-6664-4cd6-92ad-c08f0e2296ea
  app: viewing-party
  run: rails db:migrate
env:
  global:
    secure: "MQttwWxtYhIlYkgdf16tRZQ1dr1QevRIdieT9cNVQCBlxMLXlRuo1b8EDnQ0LRyfXgUQjMXkWmwdmXUSSYJM3EoznaSqp51KsrVuuqfD2tptycO/0hyLgTTPEeyajKQ03iDxUxKDw9Zo8JceX70DzxmislHdqqTa7uoFM1xzxNpCTYfOxSSt93tg9SM46oxi0Dft23W5vuuDNOw+BdWYTFnJOh/9PeMd5PKwrHC+8xSfacGOkSuu/kKLa9LZL9CPy3DGMGL8NPrhYOzZW4aATSlM+k9j87ljdXlOr9zNYeRr9U9JFjOIHVAuA1a4nGCmFvW0FQ/3ojZ3X3xdmf9lE0HQ1lT8bS5toKwpausAObx1EYDJNIf7/lqYy7aruW5XHiEebhcQG/gWD9QFGACNmhC5PxeZZ9pTG9ro9sc0GnWF9ydUOPf2msZdEsqvKeMPIolTjbsBpvhKBCR5D7QvzBuTR/ts5dQmoUs4vpl8U3kmcDKG/09H1EZu6BE1AZZqA/EDGMag7ljBXNsZyhE+QreOHDPmUSfO/tKSeXyhaxadlpxMiATo0v8iuL4hsIT4SrR+92m5v7y+ngQDvXwfQlqU0PXBM9qikjNRwCTlHGisjejwqA1e7HJe3vDdYADPCIknOOSWLrOU8bTzy+RVD8obPStTLWbprJzSdeoqp74="
