language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key: 0b886747-6664-4cd6-92ad-c08f0e2296ea
  app: viewing-party
  run: rails db:migrate
env:
  global:
    secure: ZD0JZ4p89l2DZRT1TP/9DgIX7XFGQunWDnO2W+yFerwl9QKr4DTcXaXMrASP4N4tKJar7ZtdGzZjI8v8MPq/erAKj2HD4G8jNW3t2vvn1jL4Wwtx0rSD+CX6SzcDUaOfqI614DulPl8djjK6mQ+pGCPHsnQPGM/eoY8gmXDA/TSu4ctLAeCRziDUrOpZLwyNK2XwjP79mbxz+kNsDpZlXWPmY8/q/d9IJwcPblUKHEYlk3NBPVdpHw5poa9WR/C2rNlEwjIAzYcMwkOaREiC5ZaVOeRxOi3xCW57VfKuO/M4ZJkcL7+efhK3CqnrcHz/Ny7z3NRZRDXIG//JfIeVnLUeF7ArYvDNC5X34Abv4vfyWnrZxOwiwNmKifoFAhgrBejzz6v9AbKkGWK3ZxqXsm81PYOidQwsJaUy7WcRd+ovkZNHhuoNx0tr03d4M7yFiS9vQyX08CJ+L6kolZAsg25aEJ66rGqG+4RKfMS1qupDr1Qwes+VtePeRq5PwS9F1irDy4jY9vzuYYZx6oDssD5fgCaU3mPC7PMiG0BOasPJ8nZ4E/z+cP2oRzBlNZ0eR01s8A3EprZm/MQY5owc7zRcU26zHgRb4S9Nfq7qRpzUcIOZGzi/lBkAPI9RLeJYmxjLTlEItEcIS+j1poB1Ea5yq16LbpTq4oqC9NgOqCk=
